### ISSUE TITLE
Excel Checker Version 2.0

### ISSUE THREAD

**Issue by pdrtzk** [thm-mni-ii/feedbacksystem#1041]
## Features 
- [ ] #855 
- [ ] #986 
- [ ] Automated solution and checker configuration
- [ ] Formula metrics
- [ ] Misplacement correction
- [ ] Formatting and units checking
- [ ] Custom templates for each student
- [ ] Improve feedback for docents (and tutors)

## Utilities, ...
- [ ] Generatation of dependency graph for solution file
- [ ] Support of ODF

## UI/UX
- [ ] #767 
- [ ] Improve output of excel checker results
