### ISSUE TITLE
[Math-Checker] Verbesserung

### ISSUE THREAD

**Issue by Zitrone44** [thm-mni-ii/feedbacksystem#1049]
* [ ] Beschreibung der Aufgabe in Excel
* [ ] Rote Eingabefelder für Fehlerfelder
* [ ] Mathe Editor für Abgabe
* [ ] Markdown + Latex in Beschreibung
