### ISSUE TITLE
[Epic] Mirgrate Scala Code to Kotlin

### ISSUE THREAD

**Issue by mxsph** [thm-mni-ii/feedbacksystem#1182]
Issue to track the progress of the migration from Scala to kotlin.

---

Since it is only possible to import Kotlin code into Scala, we need to start the migration from the persistence services and migrate the others later:

### Migration guide

During the migration to Kotlin, the persistent SQL queries should be migrated to [Spring Data JPA](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#preface). The following steps may be required for a successful migration:

<details>
<summary>Show Migration Steps</summary>

1. Migrate the data types used by the service to Kotlin
  **Example**: https://github.com/thm-mni-ii/feedbacksystem/blob/c8e5e428530dac2847c59b514d9b5521e53ebaf4/modules/fbs-core/api/src/main/kotlin/de/thm/ii/fbs/model/v2/checker/Runner.kt#L5-L8
  
2. Create an SQL entity class
    **Example**: https://github.com/thm-mni-ii/feedbacksystem/blob/c8e5e428530dac2847c59b514d9b5521e53ebaf4/modules/fbs-core/api/src/main/kotlin/de/thm/ii/fbs/model/v2/playground/SqlPlaygroundDatabase.kt#L7-L26
3. Create a Repository class
    **Example**: https://github.com/thm-mni-ii/feedbacksystem/blob/c8e5e428530dac2847c59b514d9b5521e53ebaf4/modules/fbs-core/api/src/main/kotlin/de/thm/ii/fbs/services/v2/persistence/SqlPlaygroundDatabaseRepository.kt#L6-L10
4. Use the Kotlin classes instead of the old ones.
5. Delete the old classes

</details>

### Services

- [ ] Migrate `CheckrunnerConfigurationService.scala` to Kotlin
- [ ] Migrate `CheckrunnerSubTaskService.scala` to Kotlin
- [ ] Migrate `CourseRegistrationService.scala` to Kotlin
- [ ] Migrate `CourseResultService.scala` to Kotlin
- [ ] Migrate `CourseService.scala` to Kotlin
- [ ] Migrate `DatabaseMigrationService.scala` to Kotlin
- [ ] Migrate `EvaluationContainerService.scala` to Kotlin
- [ ] Migrate `MinioService.scala` to Kotlin
- [ ] Migrate `SemesterService.scala` to Kotlin
- [ ] Migrate `SQLCheckerService.scala` to Kotlin
- [ ] Migrate `StorageService.scala` to Kotlin
- [ ] Migrate `SubmissionService.scala` to Kotlin
- [ ] Migrate `TaskService.scala` to Kotlin
- [ ] Migrate `UserService.scala` to Kotlin

---

**Todo: Add all packages and guides**
