### ISSUE TITLE
Add API-Endpoint for Course SubTask-Statistiks

### ISSUE THREAD

**Issue by Zitrone44** [thm-mni-ii/feedbacksystem#587]
* [x] Average points in subtask
* [x] Max points for subtask
* [x] Grouped by main task
