### ISSUE TITLE
[API] Configuration to hide the Submission result from the Student

### ISSUE THREAD

**Issue by Zitrone44** [thm-mni-ii/feedbacksystem#854]
**Is your feature request related to a problem? Please describe.**
Students are shown the result of a task everytime.

**Describe the solution you'd like**
Docents should be able to configure if the Student can see the result of a Submission.

**Tasks**

- [x] Add a Database field to store the configuration (`hideResults`)
- [x] Allow Dozents to change the configuration via the API
- [x] Hide the result if the Option is aktivated

---

required for #861
